name: Build and Push to ECR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to Backend EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          set -e

          sudo chown -R ubuntu:ubuntu /home/ubuntu/instamastadongram

          cd /home/ubuntu/instamastadongram
          git config --global --add safe.directory /home/ubuntu/instamastadongram
          git reset --hard HEAD
          git clean -fd
          git pull origin main
          cd server
          npm install
          pm2 restart instamastadongram-backend || pm2 start src/index.ts --name instamastadongram-backend
          EOF 
          
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to Frontend EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            sudo chown -R ubuntu:ubuntu /var/www/frontend
            cd /var/www/frontend
            git config --global --add safe.directory /var/www/frontend
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            cd frontend
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx
          EOF