name: Build and Push to ECR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  PROJECT_NAME: ${{ vars.ECR_REPOSITORY }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get ECR repository URLs
        id: ecr-repos
        run: |
          BACKEND_REPO_URL=$(aws ecr describe-repositories --repository-names "${PROJECT_NAME}-backend" --region $AWS_REGION --query 'repositories[0].repositoryUri' --output text)
          FRONTEND_REPO_URL=$(aws ecr describe-repositories --repository-names "${PROJECT_NAME}-frontend" --region $AWS_REGION --query 'repositories[0].repositoryUri' --output text)
          echo "backend_repo_url=$BACKEND_REPO_URL" >> $GITHUB_OUTPUT
          echo "frontend_repo_url=$FRONTEND_REPO_URL" >> $GITHUB_OUTPUT

      - name: Generate version tag
        id: version
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "version=pr-${{ github.event.number }}-${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "version=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.ecr-repos.outputs.backend_repo_url }}:${{ steps.version.outputs.version }}
            ${{ steps.ecr-repos.outputs.backend_repo_url }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ steps.ecr-repos.outputs.frontend_repo_url }}:${{ steps.version.outputs.version }}
            ${{ steps.ecr-repos.outputs.frontend_repo_url }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image URLs
        run: |
          echo "Backend image: ${{ steps.ecr-repos.outputs.backend_repo_url }}:${{ steps.version.outputs.version }}"
          echo "Frontend image: ${{ steps.ecr-repos.outputs.frontend_repo_url }}:${{ steps.version.outputs.version }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: |
          cd terraform
          terraform init

      - name: Get EC2 public IP
        id: ec2-ip
        run: |
          cd terraform
          PUBLIC_IP=$(terraform output -raw public_ip 2>/dev/null || echo "")
          if [ -z "$PUBLIC_IP" ]; then
            echo "Could not get EC2 public IP from Terraform output"
            exit 1
          fi
          echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT
          echo "EC2 Public IP: $PUBLIC_IP"

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
          chmod 600 ~/.ssh/ec2-key.pem
          ssh-keyscan -H ${{ steps.ec2-ip.outputs.public_ip }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          echo "Starting automated deployment to EC2 using Docker Compose..."

          cat > deploy-ec2.sh << 'EOF'
          #!/bin/bash
          set -e

          echo "Starting deployment on EC2 using Docker Compose..."

          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ steps.ecr-repos.outputs.backend_repo_url }}

          echo "Stopping existing containers..."
          docker-compose down || true

          echo "Pulling new images..."
          docker pull ${{ steps.ecr-repos.outputs.backend_repo_url }}:${{ steps.version.outputs.version }}
          docker pull ${{ steps.ecr-repos.outputs.frontend_repo_url }}:${{ steps.version.outputs.version }}

          echo "Creating production docker-compose.yaml with ECR images..."
          cat > docker-compose.prod.yaml << 'EOF'
          version: '3.8'
          services:
            mongodb:
              image: mongo:7.0
              container_name: ${{ vars.ECR_REPOSITORY }}-mongodb
              restart: unless-stopped
              environment:
                MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_ROOT_USERNAME }}
                MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
                MONGO_INITDB_DATABASE: ${{ secrets.MONGO_DATABASE }}
              volumes:
                - mongodb_data:/data/db
              networks:
                - app-network
              healthcheck:
                test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
                interval: 30s
                timeout: 10s
                retries: 3

            backend:
              image: ${{ steps.ecr-repos.outputs.backend_repo_url }}:${{ steps.version.outputs.version }}
              container_name: ${{ vars.ECR_REPOSITORY }}-backend
              restart: unless-stopped
              environment:
                - PORT=8000
                - MONGO_URI=mongodb://${{ secrets.MONGO_ROOT_USERNAME }}:${{ secrets.MONGO_ROOT_PASSWORD }}@mongodb:27017/${{ secrets.MONGO_DATABASE }}?authSource=admin
                - SESSION_SECRET=${{ secrets.SESSION_SECRET }}
              volumes:
                - uploads_data:/app/server/uploads
              ports:
                - "8000:8000"
              depends_on:
                mongodb:
                  condition: service_healthy
              networks:
                - app-network
              healthcheck:
                test:
                  [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:8000/health",
                  ]
                interval: 30s
                timeout: 10s
                retries: 3

            frontend:
              image: ${{ steps.ecr-repos.outputs.frontend_repo_url }}:${{ steps.version.outputs.version }}
              container_name: ${{ vars.ECR_REPOSITORY }}-frontend
              restart: unless-stopped
              ports:
                - "80:80"
              depends_on:
                backend:
                  condition: service_healthy
              networks:
                - app-network
              healthcheck:
                test:
                  [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:80/",
                  ]
                interval: 30s
                timeout: 10s
                retries: 3

          volumes:
            mongodb_data:
              driver: local
            uploads_data:
              driver: local

          networks:
            app-network:
              driver: bridge
          EOF

          echo "Starting services with Docker Compose..."
          docker compose -f docker-compose.prod.yaml up -d

          echo "Deployment completed successfully!"
          EOF

          scp -i ~/.ssh/ec2-key.pem deploy-ec2.sh docker-compose.prod.yaml ec2-user@${{ steps.ec2-ip.outputs.public_ip }}:~/
          ssh -i ~/.ssh/ec2-key.pem ec2-user@${{ steps.ec2-ip.outputs.public_ip }} "chmod +x ~/deploy-ec2.sh && ~/deploy-ec2.sh"

      - name: Wait for deployment
        run: |
          echo "Waiting 60 seconds for containers to start..."
          sleep 60

      - name: Health check backend
        run: |
          echo "Checking backend health at http://${{ steps.ec2-ip.outputs.public_ip }}:8000/health"
          for i in {1..10}; do
            if curl -f -s http://${{ steps.ec2-ip.outputs.public_ip }}:8000/health > /dev/null; then
              echo "Backend health check passed"
              break
            else
              echo "Backend health check attempt $i/10 failed, retrying in 5 seconds..."
              if [ $i -eq 10 ]; then
                echo "Backend health check failed after 10 attempts"
                exit 1
              fi
              sleep 5
            fi
          done

      - name: Health check frontend
        run: |
          echo "Checking frontend health at http://${{ steps.ec2-ip.outputs.public_ip }}"
          for i in {1..10}; do
            if curl -f -s http://${{ steps.ec2-ip.outputs.public_ip }} > /dev/null; then
              echo "Frontend health check passed"
              break
            else
              echo "Frontend health check attempt $i/10 failed, retrying in 5 seconds..."
              if [ $i -eq 10 ]; then
                echo "Frontend health check failed after 10 attempts"
                exit 1
              fi
              sleep 5
            fi
          done

      - name: Deployment summary
        run: |
          echo "Full CI/CD Pipeline Completed Successfully!"
          echo ""
          echo "Application Details:"
          echo "   Application URL: http://${{ steps.ec2-ip.outputs.public_ip }}"
          echo "   Backend API: http://${{ steps.ec2-ip.outputs.public_ip }}:8000"
          echo ""
          echo "Deployed Images:"
          echo "   Backend: ${{ steps.ecr-repos.outputs.backend_repo_url }}:${{ steps.version.outputs.version }}"
          echo "   Frontend: ${{ steps.ecr-repos.outputs.frontend_repo_url }}:${{ steps.version.outputs.version }}"
          echo ""
          echo "All health checks passed!"
          echo "Application is live and ready for use!"
